FROM ruby:3.3.4

ARG WORKDIR=/app
ENV WORKDIR=$WORKDIR
ENV BUNDLE_PATH=/usr/local/bundle
ENV GEM_HOME=/usr/local/bundle
ENV PATH="${BUNDLE_PATH}/bin:${PATH}"

RUN apt-get update -qq && \
    apt-get install -y nodejs postgresql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN gem install bundler

WORKDIR $WORKDIR

# キャッシュディレクトリを作成
RUN mkdir -p tmp/cache tmp/bootsnap

# Gemfile をコピー
COPY Gemfile Gemfile.lock ./

RUN bundle install

# アプリケーションのソースコードをコピー
COPY . .

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]