FROM ruby:3.3.4

ARG WORKDIR=/app
ENV WORKDIR=$WORKDIR

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR $WORKDIR

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

COPY . .

CMD ["rails", "server", "-b", "0.0.0.0"]