default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD") { ENV['POSTGRES_PASSWORD'] } %>
  database: <%= ENV.fetch("POSTGRES_DB", "osakana_calendar_db") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "osakana_calendar_db") %>

test:
  <<: *default
  database: osakana_calendar_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>